project:
    type: website

format:
    html:
        theme: cosmo
        css: styles.css
        toc: true

website:
    open-graph: true
    repo-actions: [issue]
    navbar:
        background: primary
        search: true
        collapse-below: lg
        left:
            # - text: "Get Started"
            #     href: getting_started.ipynb
            # - text: "Tutorial"
            #     href: tutorials/tutorial.ipynb
            # - text: "Blog"
            #     href: blog/index.qmd
            - text: "Help"
              menu:
                  - text: "Report an Issue"
                    icon: bug
                    href: https://github.com/sampath017/researchai/issues
                  - text: "Chat with dev"
                    icon: chat-right-text
                    href: mailto:sampathkovvali@gmail.com
        right:
            - icon: github
              href: https://github.com/sampath017/researchai

    sidebar:
        style: floating

metadata-files: [nbdev.yml, sidebar.yml]
