# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AI_Algorithms_Implementation',
                'doc_host': 'https://sampath017.github.io',
                'git_url': 'https://github.com/sampath017/AI_Algorithms_Implementation',
                'lib_path': 'src'},
  'syms': { 'src.nn.layers': { 'src.nn.layers.Dense': ('layers.html#dense', 'src/nn/layers.py'),
                               'src.nn.layers.Dense.__init__': ('layers.html#dense.__init__', 'src/nn/layers.py'),
                               'src.nn.layers.Dense.forward': ('layers.html#dense.forward', 'src/nn/layers.py'),
                               'src.nn.layers.spiral_data': ('layers.html#spiral_data', 'src/nn/layers.py')}}}
