# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/researchai',
                'doc_host': 'https://sampath017.github.io',
                'git_url': 'https://github.com/sampath017/researchai',
                'lib_path': 'researchai'},
  'syms': { 'researchai.nn.layers': { 'researchai.nn.layers.Dense': ('layers.html#dense', 'researchai/nn/layers.py'),
                                      'researchai.nn.layers.Dense.__init__': ('layers.html#dense.__init__', 'researchai/nn/layers.py'),
                                      'researchai.nn.layers.Dense.__str__': ('layers.html#dense.__str__', 'researchai/nn/layers.py'),
                                      'researchai.nn.layers.Dense.forward': ('layers.html#dense.forward', 'researchai/nn/layers.py'),
                                      'researchai.nn.layers.spiral_data': ('layers.html#spiral_data', 'researchai/nn/layers.py')}}}
