# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AI_Algorithms_Implementation',
                'doc_host': 'https://sampath017.github.io',
                'git_url': 'https://github.com/sampath017/AI_Algorithms_Implementation',
                'lib_path': 'AI_Algorithms_Implementation'},
  'syms': { 'AI_Algorithms_Implementation.core': { 'AI_Algorithms_Implementation.core.Dense': ( 'core.html#dense',
                                                                                                'AI_Algorithms_Implementation/core.py'),
                                                   'AI_Algorithms_Implementation.core.Dense.__init__': ( 'core.html#dense.__init__',
                                                                                                         'AI_Algorithms_Implementation/core.py'),
                                                   'AI_Algorithms_Implementation.core.Dense.forward': ( 'core.html#dense.forward',
                                                                                                        'AI_Algorithms_Implementation/core.py'),
                                                   'AI_Algorithms_Implementation.core.spiral_data': ( 'core.html#spiral_data',
                                                                                                      'AI_Algorithms_Implementation/core.py')}}}
